{{- if .Values.sloApi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slo-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-slo.labels" . | nindent 4 }}
    app: slo-api
{{- end }}
